config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/profile", to: 'pages#profile'
  get "/bookings", to: 'pages#bookings'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :toys do
    resources :offers, only: [ :index, :new, :create, :edit, :update ]
  end
  resources :offers, only: [ :show, :destroy ]
  resources :users, only: [ :show ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :toys

  validates :name, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :offer
  belongs_to :user

  validates :content, presence: true
  validates :offer_id, presence: true
  validates :user_id, presence: true
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  belongs_to :toy
  has_many :messages

  validates :start_date, :end_date, presence: true
  # start_date after current date
  # end_date after start_date
  validates :accepted, inclusion: { in: [true, false] }
end

app/models/toy.rb
class Toy < ApplicationRecord
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  belongs_to :user
  belongs_to :category
  has_many :offers

  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :user_id, presence: true
  validates :category_id, presence: true

  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :toys
  has_many :offers

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # def create
  # end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [ :update ]

  def index
    @offers = Offer.all
  end

  def show
    @offer = Offer.find(params[:id])
    @num_of_days = (@offer.end_date - @offer.start_date).to_i
  end

  # def new
  #   @toy = Toy.find(params[:toy_id])
  #   @offer = Offer.new
  # end

  def create
    @offer = Offer.new(offer_params)
    @toy = Toy.find(params[:toy_id])
    @offer.toy = @toy
    @offer.user = current_user
    if @offer.save
      redirect_to offer_path(@offer)
    else
      render 'new'
    end
  end
  
  def edit
    @offer = Offer.find(params[:id])
  end

  def update
    if params[:accepted]
      @offer.accepted = true
      @offer.save
      redirect_to bookings_path
    else
      @offer.update(offer_params)
      redirect_to offer_path(@offer)
    end
  end

  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy
    redirect_to bookings_path
  end

  private

  def set_offer
    @offer = Offer.find(params[:id])
  end

  def offer_params
    params.require(:offer).permit(:start_date, :end_date,  :toy_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  def home
  end

  def profile
    @my_toys = current_user.toys
    @my_offers = current_user.offers
  end

  def bookings
    @my_offers = current_user.offers
    @toy_requests = []
    current_user.toys.each do |toy|
      toy.offers.each do |offer|
        @toy_requests << offer
      end
    end
  end
end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    @toys = Toy.geocoded

    @markers = @toys.map do |toy|
      {
        lat: toy.latitude,
        lng: toy.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { toy: toy })
      }
    end

    # search for toys
    if params[:query].present?
      sql_query = " \
        toys.name ILIKE :query \
        OR toys.description ILIKE :query \
        OR categories.name ILIKE :query\
      "
      @toys = Toy.joins(:category).where(sql_query, query: "%#{params[:query]}%")
    else
      @toys = Toy.all
    end
  end

  def show
    @toy = Toy.find(params[:id])
    @offer = Offer.new
    @markers = [{ 
      lat: @toy.latitude,
      lng: @toy.longitude,
      infoWindow: render_to_string(partial: "show_info_window", locals: { toy: @toy })
    }]
  end

  def new
    @toy = Toy.new
  end

  def create
    @toy = Toy.new(toy_params)
    @toy.user = current_user
    if @toy.save
      redirect_to toy_path(@toy)
    else
      render 'new'
    end
  end

  def edit
    @toy = Toy.find(params[:id])
  end

  def update
    @toy = Toy.find(params[:id])
    @toy.update(toy_params)
    redirect_to toy_path(@toy)
  end

  def destroy
    @toy = Toy.find(params[:id])
    @toy.destroy
    redirect_to toys_path
  end

   private

  # def set_toy
  # end

  def toy_params
    params.require(:toy).permit(:name, :description, :price, :category_id, :photo, :location)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Toy Box</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="page-container">
      <%= render 'shared/navbar' %>
      <div class="main-content">
        <%= yield %>
      </div>
      <%= render 'shared/flashes' %>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/offers/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">

      <h1>Edit your request</h1>

      <%= simple_form_for @offer do |f| %>
      <%= f.input :start_date, as: :date, html5: true %>
      <%= f.input :end_date, as: :date, html5: true %>
      <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/offers/index.html.erb
<div class="banner">
  <h1>Offers</h1>
</div>
<ul>
  <% @offers.each do |offer| %>
  <li><%= link_to toy.name, toy_offers_path(toy) %></li>
  <%= link_to 'Edit Offer', edit_toy_offer_path(toy) %>
  <%= link_to 'Delete Offer', toy_offer_path(toy), method: :delete, data: { confirm: "Are you sure you would like to DELETE " + toy.name } %>
  <% end %>
</ul>

<%= link_to 'Add a new offer', new_toy_offer_path  %>

app/views/offers/new.html.erb
<div class="container text-center">
  <div class="row justify-content-center">
    <div class="col-md-8">

      <h1>Request <%= @toy.name %></h1>
      <%= simple_form_for([@toy, @offer]) do |f| %>
        <div class="form-inputs text-left">
          <%= f.input :start_date, as: :date, html5: true %>
          <%= f.input :end_date, as: :date, html5: true %>
        </div>
        <div class="form-actions">
          <%= f.button :submit, class: 'btn btn-toyorange'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/offers/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1 class="title">Request confirmation</h1>
      <div class="offer-info border border-secondary shadow">
        <div class="offer-text">
          <p><strong>Start date:</strong> <%= @offer.start_date %></p>
          <p><strong>End date:</strong> <%= @offer.end_date %></p>
          <p><strong>Location:</strong> <%= @offer.toy.location %></p>
          <p><strong>Number of days:</strong> <%= @num_of_days %> days </p>
          <p><strong>Status:</strong> <%= @offer.accepted ? "Accepted" : "Pending" %></p>
          <p><strong>Total price:</strong> £<%= number_with_precision((@num_of_days * @offer.toy.price), precision: 2) %></p>
          <%= link_to "Back to toys", toys_path, class: "btn btn-outline-warning" %>
        </div>
        <div class="offer-image">
          <% if @offer.toy.photo.attached? %>
            <%= cl_image_tag @offer.toy.photo.key, height: 200, width: 200, crop: :fill, class: "shadow" %>
          <% else %>
            <img src="https://source.unsplash.com/qBrF1yu5Wys/300x300/" class="shadow" style="width: 200px; height: 200px; object-fit: cover;">
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/bookings.html.erb
<div class="container bookings">
  <h2>My requests</h2>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Toy</th>
        <th>User</th>
        <th>Start date</th>
        <th>End date</th>
        <th>Price</th>
        <th>Location</th>
        <th>Status</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <% @my_offers.each do |offer| %>
      <tr>
        <td><%= offer.toy.name %></td>
        <td><%= offer.user.first_name %> <%= offer.user.last_name %></td>
        <td><%= offer.start_date %></td>
        <td><%= offer.end_date %></td>
        <td>£<%= number_with_precision(((offer.end_date - offer.start_date).to_i * offer.toy.price), precision: 2) %></td>
        <td><%= offer.toy.location %></td>
        <td class="Accepted"><%= offer.accepted ? "Accepted" : "Pending" %></td>
        <td><%= link_to "Edit", edit_toy_offer_path(offer, offer.toy), class: "btn btn-warning px-4" %></td>
        <td><%= link_to "Cancel", offer_path(offer), method: :delete, data: { confirm: "Cancel this request?" }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>

  </table>

  <h2>Requests for your toys</h2>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Toy</th>
        <th>User</th>
        <th>Start date</th>
        <th>End date</th>
        <th>Price</th>
        <th>Location</th>
        <th>Status</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <% @toy_requests.each do |offer| %>
      <tr>
          <td><%= offer.toy.name %></td>
          <td><%= offer.user.first_name %> <%= offer.user.last_name %></td>
          <td><%= offer.start_date %></td>
          <td><%= offer.end_date %></td>
          <td>£<%= number_with_precision(((offer.end_date - offer.start_date).to_i * offer.toy.price), precision: 2) %></td>
          <td><%= offer.toy.location %></td>
          <td class="Accepted"><%= offer.accepted ? "Accepted" : "Pending" %></td>
          <% if offer.accepted == false %>
            <td><%= link_to "Accept", toy_offer_path(offer.toy, offer, accepted: true), method: :put, class: "btn btn-warning" %></td>
          <% else %>
            <td id="disabled"><%= link_to "Accept", "#", class: "btn btn-warning disabled acepted-btn" %></td>
          <% end %>
          <td><%= link_to "Cancel", offer_path(offer), method: :delete, data: { confirm: "Cancel this request?" }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </table>
</div>

<script>
  var Accepted = document.querySelectorAll('.Accepted');
  Accepted.forEach((e)=>{
     if(e.textContent==="Accepted"){
     e.style.color="green";
    }
  })
</script>

app/views/pages/home.html.erb
<div class="background" style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)), url(https://source.unsplash.com/mf_3yZnC6ug)">
  <div class="welcome">
    <h1 class="font-bubblegum"><i style="font-size: 36px;" class="fas fa-robot mr-2"></i> Welcome to Toy Box</h1>
    <h3><strong>Sharing is caring!</strong></h3>
    <p><strong>Share forgotten toys, avoid clutter and spread the joy!</strong></p>
    <%= link_to toys_path, class: "btn btn-outline-warning" do %>
      <i class="fas fa-gamepad mr-2"></i> Get Started
    <% end %>
    </div>
</div>

app/views/pages/profile.html.erb
<div class="container profile-container">

  <div class="profile-page">
    <div class="profile-info">
      <h2> <i class="far fa-user-circle"></i> <%= (current_user.first_name).capitalize =%> <%= (current_user.last_name).capitalize =%> </h2>
      <p><%= current_user.email %></p>
      <p>Address: <%= current_user.address %></p>
      <%=link_to 'Edit Info', '/users/edit', class: 'btn btn-warning' %>
    </div>

    <div class="profile-listings">
      <h2>Active Listings <%= link_to "List your toy", new_toy_path, class: "btn btn-toyorange m-3" %></h2>
      <% @my_toys.each do |toy| %>

      <div class="listing">
        <div class="listing-img">
          <% if toy.photo.attached? %>
              <%= cl_image_tag toy.photo.key, height: 60, width: 60, crop: :limit %>
            <% else %>
              <img src="https://images.unsplash.com/photo-1558877385-81a1c7e67d72?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2100&q=80" />
            <% end %>
            <div class="profile-list-text"></div>
              <h5><%= toy.name %> </h5>
            <div class="text-split"></div>
          <p> Posted: <%= toy.created_at.strftime("%F") %></p>
        <%=link_to 'More', toy_path(toy), class: 'more-info' %>
        </div>

      </div>
      <% end %>
    </div>

  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    at toy box we <i class="fas fa-heart"></i> toys <%= image_tag "logo.svg", :class => "logo ml-2" %>
    <%# Icons made by <a href="https://www.flaticon.com/free-icon/user_758669" title="Kiranshastry">Kiranshastry</a> from <a href="https://www.flaticon.com/" title="Flaticon"> www.flaticon.com</a> %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
   <div class="flex-logo">
     <%= image_tag "logo.svg", :class => "logo mr-2" %>
    <h3 class="font-bubblegum">Toy Box</h3>
   </div>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto align-items-center">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Toys", toys_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "user.png", class: "avatar dropdown-toggle ml-3", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", profile_path, class: "dropdown-item" %>
            <%= link_to "Bookings", bookings_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item btn btn-warning">
          <%= link_to new_user_session_path, id: "nav-link" do%>
          <i class="far fa-user-circle"></i> Log in
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_search.html.erb
<%= form_tag toys_path, class: "submit-form", method: :get  do%>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Search for Toy or Category"
  %>
  <%= submit_tag "Search", name: nil, class: "btn btn-warning btn-search" %>
<% end %>

app/views/toys/_info_window.html.erb
<%= link_to toy_path(toy) do %>
  <div class="card-toy-map">
    <% if toy.photo.attached? %>
      <%= cl_image_tag toy.photo.key, height: 300, width: 400, crop: :fill_pad, gravity: :auto %>
    <% else %>
    <img src="https://images.unsplash.com/photo-1558877385-81a1c7e67d72?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2100&q=80" />
    <% end %>
    <div class="card-toy-info">
      <p class="card-map-category" style="background-color: <%= toy.category.colour %>;"><%= toy.category.name %></p>
      <h2><%= toy.name %></h2>
      <h3>£<%= number_with_precision(toy.price, precision: 2) %> / day</h3>
    </div>
  </div>
<% end %>

app/views/toys/_offer_form.html.erb
<div class="offer-form border border-secondary shadow">
  <%= simple_form_for([@toy, @offer]) do |f| %>
    <div class="form-container">
      <div class="text-left">
        <%= f.input :start_date, as: :date, html5: true %>
        <%= f.input :end_date, as: :date, html5: true %>
      </div>
      <div class="text-center">
        <%= f.submit "Request this toy", class: 'btn btn-toyorange'%>
      </div>
    </div>
  <% end %>
</div>

app/views/toys/_show_info_window.html.erb
<div class="p-3">
  <h3 class="m-0">Pick up location</h3>
</div>

app/views/toys/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1>Edit your <%=@toy.name %></h1>
      <%= simple_form_for(@toy) do |f| %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :price, as: :float %>
      <%= f.input :location %>
      <%= f.association :category %>
      <%= f.button :submit, class: 'btn btn-warning' %>
      <% end %>
    </div>
  </div>
</div>

app/views/toys/index.html.erb
<div class="d-flex">
  <div class="toys">
    <%= render 'shared/search' %>
    <div class="d-flex justify-content-between align-items-center">
      <h1>Available Toys</h1>
      <%= link_to new_toy_path, class: "btn btn-warning my-3" do %>
        List your toy <i class="fas fa-plus ml-1"></i>
      <% end %>
    </div>

    <% @toys.each do |toy| %>
      <%= link_to toy_path(toy) do %>
        <div class="card-toy">
          <% if toy.photo.attached? %>
            <%= cl_image_tag toy.photo.key, width: 300, height: 300, crop: :thumb %>
          <% else %>
            <img src="https://source.unsplash.com/qBrF1yu5Wys/300x300/" />
          <% end %>
          <div class="card-toy-info">
            <p style="background-color: <%= toy.category.colour %>;" class="card-toy-category"><%= toy.category.name %></p>
            <h2><%= toy.name %></h2>
            <p><%= toy.description %></p>
            <h3 class="card-toy-price">£<%= number_with_precision(toy.price, precision: 2) %> / day</h3>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <div id="map"
    style="height: 100vh;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>

app/views/toys/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8">
      <div class="list-toy-container">
        <h1 class="my-3 text-center">List your toy</h1>
        <%= simple_form_for(@toy) do |f| %>
          <%= f.input :name %>
          <%= f.input :description %>
          <%= f.input :price, label: 'Price per day', input_html: { min: "0", step: 0.1 } %>
          <%= f.input :location %>
          <%= f.association :category %>
          <%= f.input :photo, as: :file %>
          <%= f.button :submit, class: 'btn btn-warning my-3 mr-3' %>
          <%= link_to "Cancel", toys_path, class: "btn btn-outline-secondary my-3 mr-3" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/toys/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8">
      <div class="toy-info-box">
        <h2 class="mb-2"><%= @toy.name %></h2>
        <div class="d-flex">
          <div class="toy-img">
            <div>
              <p class="toy-category" style="background-color: <%= @toy.category.colour %>;"><%= @toy.category.name %></p>
            </div>
            <% if @toy.photo.attached? %>
              <%= cl_image_tag @toy.photo.key, height: 200, width: 200, crop: :fill, class: "shadow" %>
            <% else %>
              <img src="https://source.unsplash.com/qBrF1yu5Wys/300x300/" class="shadow" style="width: 200px; height: 200px; object-fit: cover;">
            <% end %>
          </div>

          <div class="toy-info">
            <p><strong>Name:</strong> <%= @toy.name %></p>
            <p class="mb-0"><strong>Description:</strong></p>
            <p><%= @toy.description %></p>
            <p><strong>Price per day:</strong> £<%= number_with_precision(@toy.price, precision: 2) %></p>
            <p><strong>Pick-up location:</strong> <%= @toy.location %></p>
          </div>
        </div>
      </div>
      
        <div>
          <% if @toy.user == current_user %>
            <%= link_to "Edit", edit_toy_path(@toy), class: 'btn btn-outline-warning ml-4 mr-0' %>
            <%= link_to "Back to toys", toys_path, class: 'btn btn-outline-secondary mx-2 my-3' %>
          <% else %>
            <%= link_to "Back to toys", toys_path, class: 'btn btn-outline-secondary mx-4 my-3' %>
          <% end %>
        </div>
    </div>

    <div class="col-4 justify-content-center">
      <% if @toy.user == current_user %>
        <div id="map"
          style="width: 300px; height: 60vh; border-radius: 4px; box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.15); margin-top: 24px;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
      <% else %>
        <%= render "offer_form", toy: @toy %>
        <div id="map"
          style="width: 80%; height: 30vh; border-radius: 4px; box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.15); margin-top: 24px; margin-bottom: 24px;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
      <% end %>
    </div>
  </div>
</div>